### ISSUE TITLE
[C2Cエンタメマッチングサービス][React]EndUser <1-31>深夜料金 | Phụ phí ban đêm

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#10]
>終了時刻が深夜24時を超えたら¥5000の超過料金をチャージアップ

①10分前に、お客様に通知することは必要ですか？

②延長料金の加算タイミングについて

サービス概要.pdfの10ページ：
>延長時は15分単位で延長料金を加算します。
>例1:0:00~1:00までの利用の場合に終了が1:13だった場合 →加算されません

C2Cエンタメマッチングサービス>OrderStatus-Action>4-2>
>例① 0:00~1:00までの利用の場合に終了が1:13だった場合 → 15分の延長料金が加算

→どちらが正しでしょうか？

③
24時を超えたら1分でも¥5000の超過料金を加算
そして、実際的に使用時間（15分単位）に基づいて加算します。

例えば、
使用ランク：VIP: 6,000Point / 30min
使用時間：9：00PM〜２：1５AM（Nextday)
→合計：
９：００〜１２：００→６,000p x ４＝２４０００p
００：００〜２：１５→２７０００p
超過料金：５０００p

④予約する時、時間を自由に設定できますか。
例えば、
9:00 pm ~ 1:00 am（Nextday)
00:00 ~ 5:00
========================Translate

Ở mục [React]EndUser mục 1-31, về phụ phí ban đêm:
>Nếu thời gian kết thúc vượt quá 24h đêm thì sẽ tính phí vượt quá là 5000 yên

(1) Có cần thông báo cho khách trước khi kết thúc 10' không?
(2) Về thời gian để tính phí gia hạn buổi đó thì tôi đang không hiểu vì ở trang 10 ở file sơ lược dịch vụ có ghi 
"Cứ 15'  vượt quá sẽ tính phí gia hạn", ví dụ 1: Trong TH dự kiến buổi đi có thời gian là 0:00 – 1:00, nếu lết thúc lúc 1:13 thì sẽ không bị tính phí.
Nhưng trong sheet orderStatus_Action 4-2 ở file chi tiết dịch vụ C2C lại ghi là " Ví dụ 1: Trong TH dự kiến buổi đi có thời gian là 0:00 – 1:00, nếu lết thúc lúc 1:13 thì sẽ bị tính phí vượt quá 15 phút". 
Vậy cho tôi hỏi cái nào là đúng?

(3) Cứ sau 24h đêm, dù chỉ quá 1' thôi cũng tính phí có phải không? 
Và việc tính phí dựa trên thời gian hai bên đã sử dụng thực tế (cứ sau 15' là bị tính gia hạn thêm) có đúng không?
Ví dụ: 
Use rank: VIP: 6000 point/ 30'
Use time: 9h tối đến 2h15 sáng （Nextday)
Tổng: 
９：００〜１２：００→６,000p x ４＝２４０００p
００：００〜２：１５→２７０００p
Tổng tiền vượt quá：５０００p

(4) Có thể thoải mái setting thời gian lúc booking
Ví dụ:
9:00 pm ~ 1:00 am（Nextday)
00:00 ~ 5:00

**Comment by akitoshi** [comment]
@UyenTran95 

> ①10分前に、お客様に通知することは必要ですか？
お客さんへの通知は必要ありません。
ただ、キャスト側がタイマーでわかるようになっている必要があります。

https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1823935184&range=D7
・終了予定10分前、終了時にタイマーでお知らせ（キャストが相手に延長有無の交渉）
・キャストの終了ボタンでポイント課金終了


> ②延長料金の加算タイミングについて
C2Cエンタメマッチングサービス>OrderStatus-Action>4-2>
例① 0:00~1:00までの利用の場合に終了が1:13だった場合 → 15分の延長料金が加算

上記が正しいです。

> ③料金の計算例

予約時の設定時間について
1-3. 設定時間 : 1時間, 2時間, 3時間, 4時間以上（4-10時間からSelect）
= 2時間15分や1時間30分などの予約はできない
= 2時間15分 = 初回予約2時間 + 延長15分

https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1823935184&range=D2

例1）
キャスト人数: 1人
ランク：VIP: 6,000P/30m
開始時刻 : 9:00PM
予約時間 : 4時間
実際の時間：9：00PM〜2:12AM（Nextday) = 4時間 + 延長:1時間15分
→
9:00PM〜00:00 → 6,000P x 6 = 36,000P (PrePaid)
00:00〜1:00 → 6,000P x 2 = 12,000P (PrePaid)
深夜料金 = 5000P (PrePaid)
延長料金 = 1:00 ~ 2:12AM (NextDay) → 6,000P x 2.5 = 15,000P（従量課金）

→ 合計: 68,000P


例2）
キャスト人数: 3人（VIPが2人, Loyal VIPが1人）
ランク：VIP: 6,000P/30m, LoyalVIP: 11,000P/30m
開始時刻 : 9:00PM
予約時間 : 4時間
実際の時間(VIP2人）：9：00PM〜2:12AM（Nextday) = 4時間 + 延長:1時間15分
実際の時間(Loyal VIP1人）：9：00PM〜2:50AM（Nextday) = 4時間 + 延長:2時間

→
計(VIP1人あたり): 68,000P
9:00PM〜00:00 → 6,000P x 6 = 36,000P (PrePaid)
00:00〜1:00 → 6,000P x 2 = 12,000P (PrePaid)
深夜料金 = 5000P (PrePaid)
延長料金 = 1:00 ~ 2:12AM (NextDay) → 6,000P x 2.5 = 15,000P（従量課金）

計(Loyal VIP1人あたり): 137,000P
9:00PM〜00:00 → 11,000P x 6 = 66,000P (PrePaid)
00:00〜1:00 → 11,000P x 2 = 22,000P (PrePaid)
深夜料金 = 5000P (PrePaid)
延長料金 = 1:00 ~ 2:50AM (NextDay) → 11,000P x 4 = 44,000P

→ 合計:  136,000P + 137,000P = 273,000P



> ④予約する時、時間を自由に設定できますか。

https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1823935184&range=D2
・1-1. 合流予定時刻 : 30分後, 60分後, 90分後, それ以外（Date Picker）

開始時刻を自由に設定できるようにして欲しいです。
ただ、15分刻みで良いかなと思っています。
例）開始時刻: 9:15PM, 予約設定時間: 2時間

**Comment by UyenTran95** [comment]
**Translate**

①Khi gần đến 0 h thì có cần thông báo cảnh bảo đến khách không

=> ko cần báo nhé. chỉ cần bên cast nhìn timer và hiểu là được.

https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1823935184&range=D7

・Trước thời gian dự định kết thúc 10 phút, và trước khi kết thức sẽ thông báo timer (Cast sẽ trao đổi với khách về việc có gia hạn hay không) 
・Kết thúc charge point bằng button kết thúc của cast キャストの終了ボタンでポイント課金終了

②Về thời gian tính thêm phí gia hạn 

C2C Entertainment matching service>OrderStatus-Action>4-2>
Ví dụ: trường hợp sử dụng từ 0:00~1:00, nếu kết thúc lúc 1:13 phút thì sẽ bị tính phí sử dụng gia hạn của 15 phút

③Ví dụ về việc tính phí cho dễ hiểu nhé

Về thời gian setting khi booking
1-3. Thời gian setting: 1 giờ, 2 giờ, 3 giờ, trên 4 giờ (Chọn từ 4 đến 10)
= ko thể booking kiểu 2 tiếng 15 phút, hay 1 tiếng 30 phút
= Nếu sử dụng 2 tiếng 15 phút sẽ có nghĩa là = 2 tiếng booking lúc đầu + gia hạn thêm 15 phút

https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1823935184&range=D2

Ví dụ1）
Số lượng cast: 1 người
Rank：VIP: 6,000P/30m
Thời gian bắt đầu : 9:00PM
Thời gian booking: 4 tiếng
Thời gian sử dụng thực tế: 9:00PM〜2:12AM（Nextday) = 4 tiếng +  gia hạn thêm 1 tiếng 15 phút
=>
9:00PM〜00:00 → 6,000P x 6 = 36,000P (PrePaid)
00:00〜1:00 → 6,000P x 2 = 12,000P (PrePaid)
Phụ thu đêm khuya = 5000P (PrePaid)
Phí gia hạn thêm = 1:00 ~ 2:12AM (NextDay) → 6,000P x 2.5 = 15,000P（従量課金）

→ Tổng cộng: 68,000P

Ví dụ2）
Số cast: 3 người（(VIP 2 người, Louyal VIP 1 người)
Rank：VIP: 6,000P/30m, LoyalVIP: 11,000P/30m
Thời gian bắt đầu: 9:00PM
Thời gian booking: 4時間
Thời gian thực tế(VIP2 ng）：9：00PM〜2:12AM（Nextday) = 4 tiếng + gia hạn: 1h15'
Thời gian thực tế(Loyal VIP1 ng）：9：00PM〜2:50AM（Nextday) = 4 tiếng + gia hạn: 2h

→
TỔNG CỘNG(Ứng với 1 cast VIP): 68,000P
9:00PM〜00:00 → 6,000P x 6 = 36,000P (PrePaid)
00:00〜1:00 → 6,000P x 2 = 12,000P (PrePaid)
Phụ thu đêm khuya = 5000P (PrePaid)
Phí gia hạn thêm = 1:00 ~ 2:12AM (NextDay) → 6,000P x 2.5 = 15,000P（trả theo lượng dùng）

TỔNG CỘNG(Ứng với 1 cast Loyal VIP): 137,000P
9:00PM〜00:00 → 11,000P x 6 = 66,000P (PrePaid)
00:00〜1:00 → 11,000P x 2 = 22,000P (PrePaid)
Phụ phí đêm khuya = 5000P (PrePaid)
Phí gia hạn thêm = 1:00 ~ 2:50AM (NextDay) → 11,000P x 4 = 44,000P (trả theo lượng dùng)

→ TỔNG CỘNG:  136,000P + 137,000P = 273,000P

④Khi booking thì có thể tự do chọn thời gian không?

https://docs.google.com/spreadsheets/d/1hNB-Oc1seonhp5wsw0GScyixDagsKQSJ5L33a82LtBw/edit#gid=1823935184&range=D2
・1-1. Thời gian dự định gặp mặt : 30 phút nữa, 60 phút nữa, 90 phút nữa, khác (Date picker)

Tôi mong muốn có thể chọn giờ bắt đầu thoải mái. Nhưng mà nếu để chọn theo kiểu 15 phút một là hay nhất (ví dụ 9:00. 9:15, 9:30 gọi là 15 phút 1)
Ví dụ）Thời gian bắt đầu lúc 9h15 và kéo dài dự định trong 2 tiếng
