### ISSUE TITLE
Orderキャンセル、返金（Refund)について | Về cancel Order, Refund

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#11]
Orderがキャンセルされた場合について確認させて頂きます。

誰が？
お客様
キャスト
管理者

いつに？
【preparing】キャスト募集中
【in_transit】手動マッチング　OR　自動マッチング
【meeting_start】キャストのタイマーSTARTが押された後

Orderをキャンセル可能ですか。
=====================Translate
Tôi muốn xác nhận một chút về trường hợp huỷ booking.
Ai có thể huỷ ? (Khách hay cast hay quản trị viên)
Khi nào có thể huỷ? (Trong thời gian tuyển cast, trong lúc tự động matching hay matching thủ công, hay sau khi cast nhấn bắt đầu)

**Comment by akitoshi** [comment]
@UyenTran95 

オーダーのキャンセルは管理者のみ可能となります。
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1687544719&range=D11
↑こちらに追記しておきました。

顧客はキャンセルすることができません。
もし、キャンセルしたい場合は管理者へ連絡する必要があります。

管理者がキャンセルする場合は返金可能です。

また、
expired
= 募集締め切りまでに募集人数が集まらなかった場合は自動キャンセル
となります。
