### ISSUE TITLE
[C2Cエンタメマッチングサービス][React]EndUser_Guest_<1-11>入金、課金、ポイントについて

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#12]
下記の認識は相違が無いかどうか、ご確認お願い致します。
①入金と課金は同じ意味です。

②入金するとwebsite内にポイントとして表示されます。
１ポイント＝？円

③決済する際、ポイントで決済不可能。延長有りANDクレジットカードが決済できなかった場合はポイントを
マイナス

**Comment by akitoshi** [comment]
@UyenTran95 

①入金と課金
→ 入金: Prepaid, Charge Points
→ 課金: Payment（Prepaid points or CreditCard Payment）

事前にカードでポイントをチャージすることが可能です。
ポイントを所持している場合、所持ポイントから優先して決済されます。
決済金額にポイントが不足している場合は、不足金額をクレジットカード決済します（登録済みクレジットカード）

②入金するとwebsite内にポイントとして表示されます。
→ 1ポイント= 1.1円
→ 購入単位= 3000Pごと

③決済する際、ポイントで決済不可能。延長有りANDクレジットカードが決済できなかった場合はポイントをマイナス
→ いえ、ポイントを所持している場合、所持ポイントから優先して決済されます。
→ 決済金額にポイントが不足している場合は、不足金額をクレジットカード決済します（登録済みクレジットカード）

延長の場合も決済の事前の与信（オーソリ）が必要です（Stripe: Capture） 
決済エラーの場合
・新しいクレジットカードの登録
・ポイントのPrepaidチャージ
をすることで、再決済することができる必要があります。
