### ISSUE TITLE
[C2Cエンタメマッチングサービス][React]EndUser_Guest_<1-21>ブロック | Block

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#13]
ブロック以後のメッセージが相手に非表示

ブロックというのは

①誰が誰をブロック？

お客様→キャスト
キャスト→お客様
キャスト＜＝＞お客様

②何をブロック？
メッセージだけブロック？
　　→いいね！しても、メッセージ送信不可能
　　チャットルームに入っている際、ブロックされる場合、相手のメッセージは非表示
　　1−1のチャットルーム場合、解散される？
　　　　　　　
・キャスト一覧にそのブロックされたキャストは残る？
・予約する際、そのブロックされたキャストは応募可能？自動マッチング？

③ブロック解除可能ですか？

=================Translate

Về tính năng block
1 - ai có thể block ai?

Khách => Cast
Cast => Khách
Khahcs <=> Cast

2 - Nếu block sẽ block cái gì
Chỉ block tin nhắn thôi à?
     => cho dù có ấn like thì cũng ko thể gửi tin nhắn đúng không? 
     => Khi đã vào phòng chat, trường hợp nếu bị block thì sẽ không hiển thị tin nhắn của đối phương nữa đúng ko?
     => Trường hợp phòng chat 1 - 1 thì có bị giải tán không

- Nếu cast bị block thì có hiển thị vào list cast không?
- Khi booking thì người đã bị block có thể ứng tuyển không? Nếu được thì có cho tự động meeting không?

3 - Có thể unblock không?

**Comment by akitoshi** [comment]
@UyenTran95 

ブロック機能
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=772264952&range=F23

ブロック以後のメッセージが相手に非表示
= 不快なユーザーを「相互」で「非表示」にできる機能

①誰が誰をブロック？
キャスト＜＝＞お客様
どちらからでもブロック可能です。

②何をブロック？
・チャットルームに入っている際、ブロックされる場合、「相手のメッセージ」は非表示
= 送信可能ですが相手には非表示になります（自分の送信メッセージは自分だけ表示）
↑こちらでお願いします。

・1−1のチャットルーム場合、解散される？
→解散されません
　
・キャスト一覧にそのブロックされたキャストは残る？
→残ります

・予約する際、そのブロックされたキャストは応募可能？自動マッチング？
→自動マッチングの選定の対象外にしていただきたいです。

③ブロック解除可能ですか？
→解除可能にしていただきたいです。
