### ISSUE TITLE
[C2Cエンタメマッチングサービス][React]EndUser_<1-4> ユーザ登録 | Đăng ký user

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#14]
FACEBOOK、電話番号などに加え、GOOGLE, LINEなどの一般的なログインオプションは？

非常に人気があり、ログイン操作も簡単ですので。特に日本人はFACEBOOKよりLINE をよく使用しますではないでしょうかね。

＝＝＝＝＝＝＝＝＝＝＝＝Translate
 Ngoài facebook, sđt có thể thêm các option đăng nhập phổ biến khác VD như sử dụng tài khoản gg, line,...không? (Vì những option này cũng khá phổ biến và đăng nhập cũng dễ dàng. Note: người Nhật thường sử dụng line nhiều hơn facebook phải không?)

**Comment by akitoshi** [comment]
@UyenTran95 

理想のログインオプションは
1. SMS (Phone Number)
2. Google
3. LINE
の3つです。

テストとして、Google認証は実装してあります。
https://github.com/akitoshi/Nom/blob/main/src/lib/firebase/client.ts 


Firebase AuthのProviderとしてGoogle / Facebook / Twitterのログインオプションは
実装がお手軽ですが、LINEの場合はカスタム認証を必要とします。
https://firebase.google.com/docs/auth/admin/create-custom-tokens?hl=ja

もし技術的に可能であれば
ぜひLINEも対応していただきたいです。


参考として
LINE-FirebaseAuth.tsx のgistをアップしておきました。
https://gist.github.com/akitoshi/636a307161e910b67a4e06e396e5515d

こちらの記事も参考になると思います。
https://qiita.com/Arahabica/items/8f5c7472ded92128535f
https://github.com/Arahabica/line-firebase-auth-sample/blob/master/functions/index.js

**Comment by UyenTran95** [comment]
@kienbkb @ngocphuongnb please confirm!

**Comment by kienbkb** [comment]
@akitoshi 
CC: @UyenTran95 @ngocphuongnb 
調査しておりました。
LINEの連携は対応可能な範囲でございます。

**Comment by UyenTran95** [comment]
@akitoshi デザインと仕様書にアップデートしていただけばと思います。
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=772264952&range=3:6

今はFacebook、SMSでログイン・登録
ご要望下記の通りでしょうかね？
SMS
Google
Line

**Comment by akitoshi** [comment]
@UyenTran95 
SMS / Google / LINE の3つでお願いします。
デザインはまた後ほど変更対応しておきますね。

Firebase Authでの認証機能の実装で問題点がありそうなので、新規でIssueを作成しておきます。
