### ISSUE TITLE
C2Cエンタメマッチングサービス [React]EndUser_ <1-42><1-43> つぶやき | Timeline

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#15]
つばやき機能につては、下記の認識で相違が無いかどうかご確認お願いします。

①お客様（男性）がプロフィール＞マイページに投稿するため機能→マイページしか表示しない。他の画面に表示？
②キャスト側が不要
③その投稿を閲覧できる対象は
・キャスト（お客様のプロファイルを見る際）
・他のお客様（不要だと思います）
③投稿へのコンメント、いいね！リアクション、NG内容を通報
は必要？

＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝Translate

Tính năng Tsubayaki (Timeline)
tôi đang hiểu là KH nam giới sẽ có thể đăng bài vài trong trang của mình. Phần này sẽ hiển thị ở màn profile của Kh nam đó thôi nhỉ. Ngoài ra còn hiển thị ở chỗ nào khác không. 

Và chỉ có các cast (nữ) mới xem được thôi phải ko? 
Xem bằng cách vào profile của KH nam. Có cần làm tính năng comment hay like cho bài đăng của KH ko

**Comment by akitoshi** [comment]
@UyenTran95 

つぶやき・メッセージ・探すなど、キャストもすることができます。
基本的に「お客様」と「キャスト」の両方が全ての機能を使うことができます。

https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=772264952&range=B47:B52

上記のシートで、キャスト → 「キャストのみ」という記載に変更しておきました。

--

①お客様（男性）がプロフィール＞マイページに投稿するため機能→マイページしか表示しない。他の画面に表示？
→1. 「お客様」と「キャスト」のマイページに自分の投稿が一覧表示
→2. サービス利用者全員の投稿一覧画面があります ( /timeline )
https://docs.google.com/spreadsheets/d/1
![ScreenShot_2021-05-20_10 25 19](https://user-images.githubusercontent.com/113367/118904943-cdbce700-b955-11eb-9a3c-912ae89ae219.gif)
_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1279752274&range=A14:A16

/timeline : タイムライン（投稿一覧）
/timeline/[uid]/[postId] : 投稿詳細
/timeline/post : 投稿画面

補足）
お客様 → お客様 への「メッセージ」「フォロー」はできません
キャスト → キャスト への「メッセージ」「フォロー」はできません


②キャスト側が不要
→ キャストも必要です

③その投稿を閲覧できる対象は
→「お客様」：「お客様」と「キャスト」の投稿
→「キャスト」：「お客様」と「キャスト」の投稿

・キャスト（お客様のプロファイルを見る際）
・他のお客様（不要だと思います）

③投稿へのコンメント、いいね！リアクション、NG内容を通報は必要？
→ 投稿へのコメント : 不要です
→ 投稿へのいいね！アクション : 必要です
　→いいね数の表示【likeCount: Int】、いいね！のキャンセル可能、誰からのいいね！か不要）
→ 投稿への通報 : 必要です（管理者への不適切報告）
→ 投稿の非表示機能：不要です（管理者のみ特定の投稿を全体から非表示にできる） isShowed: false
→ 投稿者の投稿全てを非表示機能：不要です


参考）
posts:
	documentID:
	postId: uid
	body: String
	imageURL: String 
	createdAt: Timestamp
	likeCount: Int

Firebase Resize Images Extensions : https://firebase.google.com/products/extensions/storage-resize-images?hl=ja

**Comment by UyenTran95** [comment]
Translate
Các tính năng như "đăng bài viết (tsubayaki), nhắn tin, search" thì phía cast cũng có thể làm được. 
Cụ thể là "KH" và "Cast" có thể sử dụng tất cả các chức năng.

https://docs.google.com/spreadsheets/d/1hNB-Oc1seonhp5wsw0GScyixDagsKQSJ5L33a82LtBw/edit#gid=772264952&range=47:52

Ở trong sheet trên, tôi đã bổ sung thêm, phần "chỉ cast mới có tính năng đó"

--

①Q: Tôi đang hiểu là KH nam giới sẽ có thể đăng bài vào trong trang của mình. Phần này sẽ hiển thị ở màn profile của Kh nam đó thôi nhỉ. Ngoài ra còn hiển thị ở chỗ nào khác không.

→1. 「お客様」と「キャスト」のマイページに自分の投稿が一覧表示
→2. Sẽ có một màn hình gồm list các bài đăng của tất cả mọi người sử dụng dịch vụ bao gồm cả KH và Cast (Timeline)
https://docs.google.com/spreadsheets/d/1hNB-Oc1seonhp5wsw0GScyixDagsKQSJ5L33a82LtBw/edit#gid=1279752274&range=14:16

/timeline : Timeline (List bài đăng)
/timeline/[uid]/[postId] : Chi tiết bài đăng
/timeline/post : Màn hình đăng bài

Bổ sung）
KH  → sẽ không thể gửi tin hay follow 1 KH khác
Cast → sẽ không thể gửi tin hay follow 1 Cast khác

ScreenShot_2021-05-20_10 25 19 (xem ở post trên)

②Phía cast có cần đăng bài không?
→Phía cast cũng cần

③Các đổi tượng có thể xem đăng bài
→「KH」：Có thể xem bài đăng của KH khác và cast
→「」：Có thể xem bài đăng của KH và cast khác

③Có cần tính năng comment, like, reaction, report nội dung ko?
→ Coment: ko cần
→ Like!: cần
　→Hiển thị số like【likeCount: Int】, có thể unlike, không cần hiển thị like của ai
→Report bài đăng: cần thiết (Sẽ report nội dung ko thích hợp đến admin)
→ Chức năng ko hiển thị bài đăng：KO cần (chỉ admin mới có thể ẩn bài đăng của user khỏi toàn bộ trang)isShowed: false
→ Chức năng ẩn tất cả bài đăng của người đăng: ko cần

Tham khảo）

posts:
  documentID:
  postId: uid
  body: String
  imageURL: String 
  createdAt: Timestamp
  likeCount: Int
Firebase Resize Images Extensions : https://firebase.google.com/products/extensions/storage-resize-images?hl=ja
