### ISSUE TITLE
[C2Cエンタメマッチングサービス]OnlineStatus

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#17]
OnlineStatusについて：
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=44678325

1 - 下記の認識は合っていますか？
キャスト：online, idle, doing, ready, busy
ゲスト：online, idle, busy

2 -　ステータスは手動変更できますか？
![May-20-2021 13-43-14](https://user-images.githubusercontent.com/84315397/118939870-5b123280-b97a-11eb-9133-44ca96057752.gif)

3 - onlineのステータスについて、下記のように２つに分られます。

(1.1) Online
(1.2)最終オンライン日時から24時間以内
ex: 30分前オンライン

Case1:
PC：Websiteにログイン済みで、ページを開いている
SP（スマホ）：Websiteにログイン済みで、ページを開いている
→ (1.1)

Case2: 
PC：Websiteにログイン済みで、ページを開いているが、Browser別のタブを閲覧中とか、別のアプリケーションを起動中
SP：Websiteにログイン済みで、ページを開いているが、Browser別のタブを閲覧中とか、別のアプリケーションを起動中
→(1.2)

Case3:
PC：Websiteにログイン済みで、スリープ中
SP：Websiteにログイン済みで、OFF中（電池ボタンを押した後）
→(1.2)

Case4:
PC：Websiteをログアウト済み OR Browserを閉じる
SP：Websiteをログアウト済み OR Browserを閉じる
→(1.2)
 
4 - doingのステータスについて、下記のように２つに分られます。

キャストがMeetingタイマーをSTART押した後、doingになります。
キャストがMeetingタイマーをEND押した後、Onlineに戻します。

5 - Ready
```
待機中で出勤可能な状態
自動で翌朝5時にオフになる
仕事中(3.doing)の間はオフになる
```

-　ReadyとOnlineはどう違いますか？
-　自動で翌朝5時にオフになる 
→毎日5時に自動的にReadyをOFFにしますか？何時までですか？
-　ReadyがOFFのカストにキャストへリクエストを通知しますか？（予約がある時）

6 - Busy.
-　手動で変更可能という認識は合っていますか？
-　手動で変更可能という認識は合っていますか？
-　目的としては、通知をプッシュしないようにするだけでしょうか？
- 　メールにも通知しませんね

**Comment by UyenTran95** [comment]
**Translate**

1 - Tôi đang hiểu, Cast sẽ có cả 5 status
online, idle, doing, ready, busy

Còn KH sẽ chỉ có 3 status là
online, idle, busy

2 - User có thể tự đổi trạng thái của các trạng thái này ko?
May-20-2021 13-43-14

3 - Về status Online tôi đang hiểu ntn. Trong status online sẽ chia thành 2 loại:

(1.1) Online = đang mở website
(1.2) Online cách đây xx phút/giờ = trong vòng 24 tiếng kể từ lần online cuối cùng.

Case1:
Trên PC, đã đăng nhập vào website và đang mở xem website => (1.1)
Trên SP, đã đăng nhập vào website và đang mở xem website => (1.1)

Case2:
Trên PC, đã đăng nhập vào website, nhưng đang ko xem website (Đang xem tab khác trên cùng trình duyệt/đang chạy 1 ứng dụng khác) => (1.2)
Trên SP, đã đăng nhập vào website nhưng đang xem tab khác của cùng trình duyệt OR đang chạy ứng dụng khác => (1.2)

Case3:
Trên PC, đã đăng nhập vào website, nhưng sleep máy => (1.2)
Trên SP, đã đăng nhập vào website nhưng đang tắt máy => (1.2)

Case4:
Trên PC: Logout OR ấn X trên trình duyệt (1.2)
Trên SP: Logout hoặc tắt trình duyệt (ấn x hoặc Vuốt từ dưới vuốt lên) (1.2)

4 - Về status "doing". Tôi đang hiểu là khi cast ấn "bắt đầu" sau khi gặp mặt với khách là sẽ tự động chuyển sang "doing" có đúng ko. Ngoài ra khi đã thành "doing" thì cast có thể đổi status đc ko?

5 - Ready

待機中で出勤可能な状態
自動で翌朝5時にオフになる
仕事中(3.doing)の間はオフになる
Ready với Online khác nhau ở chỗ nào?
自動で翌朝5時にオフになる => sẽ OFF flag vào 5 giờ sáng hàng ngày? vậy sẽ off đến khi nào?
Ready sẽ tự động hay bằng tay?
Khi ready flag off thì có thể nhận thông báo có booking từ KH ko?
6 - Busy.
Cái này tôi đã hiểu là có thể đổi bằng tay, mục đích chỉ là để nhận / ko nhận noti.
Và nếu ON thì sẽ ko nhận cả trong website lẫn email phải ko.

**Comment by akitoshi** [comment]
@UyenTran95 

OnlineStatusについて：
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=44678325

```
1 - 下記の認識は合っていますか？
キャスト：online, idle, doing, ready, busy
ゲスト：online, idle, busy

```
↑上記で合っています。


```
2 -　ステータスは手動変更できますか？
```

D列「Toggle」でreadyとbusyはToggleで手動変更できます。
ex) isReady: true, isBusy: true

online, idle, doing のステータスに関しては自動で変更されるので
ユーザーが手動変更することができません。


```
3 - onlineのステータスについて、下記のように２つに分られます。
```

online/idleのステータスに関してですが
「ページを開いている」などの判定ではなく

最終ログイン日時を
**lastLoginAt: Timestamp** 
のように保持していて
lastLoginAtと現在時刻の比較で判定していただきたいです。


```
4 - doingのステータスについて、下記のように２つに分られます。
キャストがMeetingタイマーをSTART押した後、doingになります。
キャストがMeetingタイマーをEND押した後、Onlineに戻します。
```


上記でよろしくお願いします。


```
5 - Ready
待機中で出勤可能な状態
自動で翌朝5時にオフになる
仕事中(3.doing)の間はオフになる

-　ReadyとOnlineはどう違いますか？
-　自動で翌朝5時にオフになる
→毎日5時に自動的にReadyをOFFにしますか？何時までですか？

```

ReadyはToggleで手動変更することができます。
例えば
・「本日の出勤可能なキャスト」という一覧
にも活用できると思っています。

手動で変更できるので、自動オフを付けておかないと
1週間ずっと `isReady: true` の状態が続くため
「翌朝5時に自動オフ」という機能が必要です。

キャストは毎日5:00AM以降に
`isReady: false` → `isReady: true`
に変更する必要があります。

```
-　ReadyがOFFのカストにキャストへリクエストを通知しますか？（予約がある時）
```
はい。ReadyがOffのキャストにもリクエストを通知してください。


```
6 - Busy.
-　手動で変更可能という認識は合っていますか？
-　目的としては、通知をプッシュしないようにするだけでしょうか？
```
はい、手動で変更可能です。
`isBusy: true` のキャストには通知を送らないようにして欲しいです。

**Comment by UyenTran95** [comment]
Translate:
Về phần OnlineStatus:
https://docs.google.com/spreadsheets/d/1hNB-Oc1seonhp5wsw0GScyixDagsKQSJ5L33a82LtBw/edit#gid=44678325

1 - Tôi đang hiểu như dưới đây có đúng ko?
Cast：online, idle, doing, ready, busy
Guest：online, idle, busy

Đúng rồi

2 - Q: Các Status trên có đổi bằng tay được không?
      A: trạng thái ready và busy có thể thay đổi tay bằng Toggle

ex) isReady: true, isBusy: true

Các trạng thái online, idle, doing thì sẽ được thay đổi tự động, nên user không thể tự thay đổi. 

3 - Q: Về status Online thì tôi đang hiểu sẽ được chia ra làm 2 kiểu như dưới đây. 

Liên quan đến online/idle thì không phải là việc phân định xem có đang mở page hay không.

Sẽ lưu một cái thời gian ngày giờ login cuối kiểu như là lastLoginAt: Timestamp
và sẽ phân định trạng thái khi so sánh lastLoginAt với thời gian hiện tại.

4 - Về status doing, sẽ được chia làm 2 kiểu như dưới đây.
Cast sau khi ấn START timer thì sẽ thành "Doing"
Cast sau khi ấn END timer thì sẽ trả về "Online" 

Hãy làm như trên nhé. 

5 - Ready
Q:
```
Là trạng thái đang chờ và có thể đi làm
Tự động OFF vào 5giờ sáng hôm sau
Khi đang là Doing thì sẽ thành OFF

-　Ready với Online khác nhau ntn?
```

Ready là trạng thái có thể thay đổi tay bằng Toggle
Ví dụ: 
・Tôi nghĩ là có thể tận dụng nó vào cả Trong list "Cast có thể đi làm hôm nay"

Do cast có thể tự thay đổi trạng thái này bằng tay, nên cần phải có một chế độ cho tự động OFF
Nếu không thì sẽ có trạng thái suốt 1 tuần  isReady: true

Nên sẽ cần một chức năng: tự động OFF vào 5h sáng hôm sau. 

Sau 5:00 AM mỗi sáng, cần thay đổi
isReady: false → isReady: true

-　Q:Có thông báo tuyển dụng đến các Cast đang trong trạng thái Ready OFF hay không?
=> A:Vâng, vẫn thông báo cho tôi.

6 - Busy.
Q:
- Tôi đang hiểu là sẽ thay đổi thủ công được đúng ko?
-Và mục đích của trạng thái này chỉ là push hay ko push noti thôi đúng ko?　

Vâng, có thể thay đổi bằng tay.
isBusy: true thì sẽ không gửi bất cứ

**Comment by UyenTran95** [comment]
@akitoshi 
`lastLoginAtと現在時刻の比較で判定はどうでしょうか？
`
OKです！
他のは了解しました。ありがとうございます。
