### ISSUE TITLE
[C2Cエンタメマッチングサービス]Matching Logic, Area

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#18]
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1122007238
１）ゲストとキャストの時間課金マッチング
→ちょっと意味が分かりませんので、ご説明お願い致します。

２）対応エリア内+空き日程のキャストに通知→リクエスト受付→自動マッチング

→ゲストと同一エリアではなければ、キャストへリクエスト通知しないという認識で合っていますか？

３）エリア一覧を教えていただけませんか。ゲストはプロフィールを入力する際、エリアを選択することが必要と思います。
---------------------------------------Translate-------------------------------------------------------------
1) Tôi đang không hiểu chỗ "Matching thanh toán thời gian sử dụng của 2 bên", bạn có thể giải thích kỹ hơn giúp tôi không?
2) Thông báo đến cast đang trống lịch và ở trong khu vực tương ứng -> nhận request -> matching tự động. Chỗ này tôi đang hiểu là nếu cast không cùng trong một khu vực với guest thì sẽ không thể gửi request đến cast được, như vậy có đúng không?
3) Vui lòng cho tôi xin danh sách khu vực. Tôi nghĩ khách cũng nên chọn khu vực khi cung cấp profile của mình, bên bạn thấy sao?

**Comment by akitoshi** [comment]
@UyenTran95 

https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1122007238
↑
上記の「マッチングロジック」シートは整理できていないため
「OrderStatus-Action」「OrderType-Menu」シートの参照をよろしくお願いします。https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1823935184


```
１）ゲストとキャストの時間課金マッチング
```
→ 時間課金マッチング
= マッチング後に時間での従量課金で会うことができます。
例）60分 11000円, 延長30分 5500円



```
２）対応エリア内+空き日程のキャストに通知→リクエスト受付→自動マッチング
ゲストと同一エリアではなければ、キャストへリクエスト通知しないという認識で合っていますか？
```
→ はい。実際に出会うサービスのため、同一エリアの必要があります。
例）大阪-梅田, 東京-六本木, Honoi-OldQuarter

そのためキャスト側がリクエスト通知がくるエリアを事前に選択しておく必要があります。



```
３）エリア一覧を教えていただけませんか。ゲストはプロフィールを入力する際、エリアを選択することが必要と思います。
```
→ 下記のシートに記載しておきました。
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=173471948

都道府県(親)とエリア(子)があります。
増減があると思いますので柔軟に設計していただけると嬉しいです。
- isPublished: true

参考して、area.json を下記にアップしてあります。
https://gist.github.com/akitoshi/3bce636001832f401ab038f9bb3fe67e

**Comment by akitoshi** [comment]
@UyenTran95 

参考イメージ
![ScreenShot_2021-05-21_16 06 08](https://user-images.githubusercontent.com/113367/119096428-8e25f600-ba4e-11eb-8681-735c2f949d5b.gif)

**Comment by UyenTran95** [comment]
Về matching:

１）Matching theo thời gian sử dụng và thanh toán của Khách với Guest 
→ 時間課金マッチング
= マッチング後に時間での従量課金で会うことができます。
例）60分 11000円, 延長30分 5500円

２）thông báo đến các cast ở trong cùng khu vực và có thời gian trống => tiếp nhận request => tự động matching 
Tôi đang hiểu là nếu không ở cùng một area thì sẽ không thông báo request ứng tuyển đến cast có phải không?
→ Vâng, do đây là dịch vụ gặp mặt thực tế nên cần phải ở cùng 1 vùng mới được.
Ví dụ: Osaka-Umeda, Tokyo-Roppongi, Hanoi-OldQuarter

Do đó cần phải chọn trước khu vực sẽ gửi request đến cast

３）Hãy cho tôi biết danh sách area được không. Vậy khi guest nhập profile thì cũng cần nhập area nhỉ? 
→ Tôi đã thêm vào sheet dưới đây. 
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=173471948

Sẽ có cấp cha là 都道府県 prefecturem và cấp con là area
Tôi nghĩ sau này sẽ có trường hợp tăng / giảm nên nhờ bạn thiết kế linh hoạt giúp nhé.

isPublished: tru 参考して、area.json を下記にアップしてあります。
https://gist.github.com/akitoshi/3bce636001832f401ab038f9bb3fe67e
