### ISSUE TITLE
[Design][MyPage]

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#24]
![image](https://user-images.githubusercontent.com/84315397/119437683-dc860e00-bd48-11eb-992f-6a40f49fcfa0.png)
UserNameの下に「Name」ではなく、「注文履歴を確認する」で、クリックすると注文履歴に遷移という認識が合っていますか？

上にハートアイコンもどういう機能かもご確認おねがいします。

**Comment by akitoshi** [comment]
@UyenTran95 

MyPageをわかりやすく変更しておきました。
https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=350%3A1

ポイント履歴 = ポイントの増減 = 注文履歴
ハートアイコン ← 削除しました

https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=772264952&range=E12:E15
