### ISSUE TITLE
[Design]Profile Detail, Profile Review

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#25]
1. https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=772264952&range=17:17
(1-15) プロファイルプレビューについて、下記の認識で相違が無いでしょうか？

自分のプロフィールを編集・更新する際、「プレビュー」のようなボタンをクリックすると、他人に対して自分のプロフィールはどういうイメージかプレビューできる機能です。ここで閲覧だけです。

こういう流れです。
`My page → Profile → Edit profile / Profile preview
`
上記の認識が相違が無ければ、プレビューのデザインをご共有して頂けばありがたいです。

2. 現在のデザインの通りに、キャストのプロファイルだけですが、
ゲストのデザインはまだありません。こちらもご共有して頂けば幸いです

=========Translate

Về tính năng preview profile (1-15) tôi đang hiểu như dưới đây có đúng không?
Khi sửa hay update profile của mình thì sẽ có thêm một button kiểu dạng như "preview" và ở màn đó mình sẽ xem được profile của mình sẽ hiện ra như thế nào đối với người khác. Và ở màn này sẽ chỉ xem được thôi.

Nó sẽ theo flow như thế này
`My page → Profile → Edit profile / Profile preview
`

Nếu ý hiểu trên đúng thì nhờ bạn cung cấp design giúp nhé.

2. Design hiện tại tôi thấy mới chỉ có design cho profile của cast. vẫn chưa có của guest. nhờ bạn design giup nhé.

**Comment by akitoshi** [comment]
@UyenTran95 

```
自分のプロフィールを編集・更新する際、「プレビュー」のようなボタンをクリックすると、他人に対して自分のプロフィールはどういうイメージかプレビューできる機能です。ここで閲覧だけです。
My page → Profile → Edit profile / Profile preview
上記の認識が相違が無ければ、プレビューのデザインをご共有して頂けばありがたいです。
```

そうです。自分のProfile Preview Page は自身のページですので
キャストから見たページと同様になります。
URL = xxx.com/[my uid] 
となります。
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1279752274&range=B27

- [x]  Add Preview Page
https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=350%3A1007

https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=772264952&range=D17
