### ISSUE TITLE
[Common]CastとGuestの確認

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#27]
下記の認証は相違が無いかどうかお確認御願い致します。
- 検索
Cast→Guestを検索できる
Guest→Castを検索できる
Cast→Castを検索でない →プロフィールを閲覧不可能→いいね、フロー不可能
Guest→Guestを検索でない→プロフィールを閲覧不可能→いいね、フロー不可能

- チャット
Cast→Guestをチャットできる
Guest→Castをチャットできる
Cast→Castをチャットでない
Guest→Guestをチャットでない

- マッチング
Guest→Castを予約できる
Cast→Guestから予約を受ける

- つばやき
Cast, Guestは投稿できる
Cast, Guest→Cast,Guestから予約を受ける
Guest→Cast,Guestから予約を受ける

Về tương tác giữa Cast Và Guest tôi đang hiểu như dứoi đây:

- Search:
Cast => có thể search Guest
Guest => có thể search Cast
Cast ko thể search Cast, Guest ko thể search Guest

- Chat:
Cast => có thể chat Guest
Guest => có thể chat Cast
Cast ko thể chat Cast, Guest ko thể chat Guest

- Matching:
Guest => có thể booking Cast
Cast => có thể nhận booking

- Tweet:
Cast, Guest có thể đăng bài, xem bài của cả hai bên

**Comment by akitoshi** [comment]
@UyenTran95 

はい、その通りです。

```
Search: 検索
Cast→Guestを検索できる
Guest→Castを検索できる
Cast→Castを検索でない →プロフィールを閲覧不可能→いいね、フロー不可能
Guest→Guestを検索でない→プロフィールを閲覧不可能→いいね、フロー不可能

Chat: チャット
Cast→Guestをチャットできる
Guest→Castをチャットできる
Cast→Castをチャットでない
Guest→Guestをチャットでない

Matching: マッチング
Guest→Castを予約できる
Cast→Guestから予約を受ける

Tweet: つぶやき
Cast, Guestは投稿できる
```
