### ISSUE TITLE
[Design][EndUser] Search

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#29]
![image](https://user-images.githubusercontent.com/84315397/119811143-f6724d00-bf10-11eb-99b1-ee97d10af729.png)

一覧取得から、Searchboxをクリックすると、別の画面に開いて、ここでフリーテキストと絞り込みで検索できます。
デザインはまだありませんので、できる限りご共有お願い致します。
また、
フリーワード検索というのはどんな価値から検索する機能でしょうか？

**Comment by akitoshi** [comment]
@UyenTran95 
検索画面を作成してあります。

- [x] Search Page
https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=407%3A21

### 検索結果の表示について
検索前 = Recommend Casts
検索後 = Search Result
検索画面でクリア（検索内容をReset） = Recommend Casts

![ScreenShot_2021-05-31_14 12 08](https://user-images.githubusercontent.com/113367/120143686-8834cf80-c21b-11eb-94f4-ae0553b4b36e.png)

--

また、30分あたりのポイントはこのようなイメージです
→ https://tailwindcomponents.com/component/multi-range-slider

![image](https://user-images.githubusercontent.com/113367/120143730-9da9f980-c21b-11eb-95f1-784a002c1dd3.png)

**Comment by UyenTran95** [comment]
Tôi đã tạo design cho tính năng search

Search Page
https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=407%3A21

Ở màn home bên dưới cái search box là chỗ để hiển thị kết qủa search. 
Trước khi search (Mặc định) = Recommend Casts = random list 100 cast có lượt like nhiều nhất ở cùng khu vực area 
Sau khi search = Search Result
Khi ấn clear ở màn search (reset điều kiện search)  = Recommend Casts
