### ISSUE TITLE
[Design][Enduser]Home NewCast, New Activitives, Reccomend

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#30]
1-37 => 1-39 https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=772264952&range=36:38
キャスト一覧で
![image](https://user-images.githubusercontent.com/84315397/119812154-0e969c00-bf12-11eb-9de9-8d39f110e53c.png)
```
Recent =>　ログイン順 | 最終オンライン日時表示
Reccomend =>　同じエリアでいいね！が多い人のTOP100をランダム表示
```

下記のItemはデザインに反映されていませんので、ご確認お願い致します。
`新メンバー | 登録日から1週間
`

**Comment by akitoshi** [comment]
@UyenTran95 
こちら追加しておきました
<img width="375" alt="1-34,35,36  Home@2x" src="https://user-images.githubusercontent.com/113367/120123827-2610a600-c1ec-11eb-8774-68fa6a4f63b1.png">

New Cast → 登録日から1週間
Recent → New Activities = ログイン順 | 最終オンライン日時表示
Recommend 

https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=353%3A748

**Comment by UyenTran95** [comment]
@akitoshi 

New Cast → 登録日から1週間

登録日から本日まで１日間、２日間…７日間であればNew Castになるということでしょうかね？
New Castがいない場合、NewCastのSectionを全て非表示にしていいでしょうか？「データがありません」という文言を真ん中に？
サーチ結果も、データが無い場合も、Defaultとして「データがありません」でよろしいでしょうか？

**Comment by akitoshi** [comment]
@UyenTran95 

良いフィードバックありがとうございます。

```
登録日から本日まで１日間、２日間…７日間であればNew Castになるということでしょうかね？
```
はい、登録日から7日間はNew Castになります。

```
New Castがいない場合、NewCastのSectionを全て非表示にしていいでしょうか？
```
New Castセクションを全て非表示でお願いします。
「データがありません」という文言は必要ありません。

サーチ結果が無い場合は
`検索条件に合うキャストがいません`
`条件を変えて、もう一度好みのキャストを探しましょう。`

といった文言を追加して欲しいです。
また、空白のコンテンツを避けるために、Recommend Castを再表示して欲しいです。

![ScreenShot_2021-06-01_10 54 14](https://user-images.githubusercontent.com/113367/120256008-2da57d00-c2c8-11eb-83c5-0b41a7bc67bf.png)


https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=495%3A4797
