### ISSUE TITLE
[Design][Common]

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#35]
現在のデザインはMobileに対してOKですが、PCにアクセスすると、右と左は白い空になります。
そのままで大丈夫でしょうか？
<img width="1440" alt="Screen Shot 2021-05-31 at 09 35 47" src="https://user-images.githubusercontent.com/84315397/120156509-3f314b00-c21c-11eb-96af-996de8d04270.png">

à còn một phần nữa là cái layout của họ em  design là sẽ cho màn mobile luôn (375px) thì lúc ở trên desktop thì có có 2 khoảng bị thừa ở 2 bên thì mình cũng cần design màu background cho 2 phần thừa này thì bên khách muốn tự chọn màu hay bên mình sẽ chọn luôn]]

**Comment by akitoshi** [comment]
@UyenTran95 

今回のケースでは
エンドユーザー（ゲスト・キャスト）からのアクセスは
Smartphoneからのアクセスを誘導するために
PCビューは無しで良いと思っています。

ただ、コンポーネントのLoadingを無くすのではなく
管理者はChrome Dev Toolから確認できるように
CSSでの非表示でお願いしたいです。

https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=494%3A726

```
// pc , tailwindCSS
<div className="hidden sm:flex sm:justify-center sm:flex-col sm:h-screen">

// mobile , tailwindCSS
<div className="block sm:hidden">
```

PCで表示されるコンポーネントに関しては
LPになりますので
今回は空白で大丈夫です。

https://user-images.githubusercontent.com/113367/120267526-145bfb00-c2df-11eb-990f-e772f4cd4330.mp4

スマホビューですが
```
iPhoneSE: 320x568
iPhoneX: 375x812
iPhone12: 390x844
iPhone12ProMax : 428x926
```

これらの多様なモバイルデバイスでも対応できるように
Fixed Layoutではなく
margin, padding を活用したコンポーネントでのmarkupをお願いできませんか？

よろしくお願いします。

**Comment by UyenTran95** [comment]
Đối với trường hợp này,
Để hướng cho enduser (Guest/cast) truy cập từ Smartphone
tôi nghĩ không nên có View cho PC. 

Tuy nhiên sẽ không phải là bỏ cái loading component
mà tôi muốn ẩn hiển thị bằng CSS để Admin có thể xác nhận từ Chrome Dev Tool

https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=494%3A726

// pc , tailwindCSS
<div className="hidden sm:flex sm:justify-center sm:flex-col sm:h-screen">
 
// mobile , tailwindCSS
<div className="block sm:hidden">
```
 
Liên quan đến cái component được hiển thi trên PC
do nó sẽ là LP nên lần này cứ để khoảng trắng cũng được, ko sao.

ScreenShot_2021-06-01_13.40.43.mp4 
Đối với view màn 

```
iPhoneSE: 320x568
iPhoneX: 375x812
iPhone12: 390x844
iPhone12ProMax : 428x926
```
 
Tôi muốn có thể đối ứng đã dạng trên các thiết bị
Nên sẽ không làm theo kiểu Fixed Layout
Mà sẽ markup bằng component sử dụng margin, padding có được không?

**Comment by t-Ac3** [comment]
@UyenTran95 theo em hiểu thì từ màn hình 640px trở xuống thì sẽ hiển thị component như bình thường còn trên 640px thì sẽ ẩn component đi và hiển thị 1 trang trắng (có kèm message nếu cần thiết)

**Comment by akitoshi** [comment]
@t-Ac3 
@UyenTran95 

サービス全体のメイン画面は640px以下でのみ表示される。
640px以上の画面では、以下の guide.tsx コンポーネントのみ表示される。

また後日にguide コンポーネントが完成したらプルリクエストを送るので、良かったらまたレビューお願いします。

--

The main screen of the entire service will be displayed only at 640px or smaller.
On screens larger than 640px, only the following guide.tsx component will be displayed

I'll send you a pull request later when the guide.tsx component is completed, so please review it again if you like.


**src/components/guide.tsx**
```
import type { VFC } from "react";

export const Guide: VFC = () => {
  return (
    <div className="hidden sm:block">
      <p>Hello Nom, min-width:640px</p>
    </div>
  );
};

```

**Comment by t-Ac3** [comment]
@akitoshi 
I've got your point. I'll review your PR when it's ready.
