### ISSUE TITLE
[Design][Enduser] Search

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#37]
![image](https://user-images.githubusercontent.com/84315397/120264013-16b25b00-c2c7-11eb-8e61-9e69db84aeaa.png)
すみませんが、ちょっと意味が分からなくて、
いつModal形で表示するか？いつ別の画面で表示するかご確認御願い致します。

**Comment by akitoshi** [comment]
@UyenTran95 

Modal表示： こちら無し
https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=354%3A0

代わりにページでの表示でお願いします。
https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=407%3A21

![ScreenShot_2021-06-01_13 01 26](https://user-images.githubusercontent.com/113367/120264903-c09ae300-c2d9-11eb-8f39-96d62a4c791b.png)
