### ISSUE TITLE
[Design][EndUser] Set up step 2

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#38]
![image](https://user-images.githubusercontent.com/84315397/120267876-07371000-c2cf-11eb-98b9-97f6fb573147.png)
飲み方ではMulti Select 可能でしょうか？

**Comment by akitoshi** [comment]
@UyenTran95 

良いフィードバックありがとうございます。
飲み方のみ、Multi Select 不可でお願いします。
