### ISSUE TITLE
[Design][EndUser] Set up step 3

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#40]
![image](https://user-images.githubusercontent.com/84315397/120300637-50e72100-c2f6-11eb-9698-df771fe9a482.png)

Step 3に表示されるキャストリストですが、
Same location areaの意味がわかりますが、Step3までユーザーは「エリア」を選択できる項目がありませんので、ユーザーのエリアを取得できませんね。
ご確認御願いします。

また、
エリアは「よく遊ぶ場所を1箇所選択する」に関係が無いでしょうかね。

ちなみに、キャストリストは何件まで表示しますか？
いいねをせずに、もしくは一件、二件しかいいねをしない場合、「完了」を押せますか？
=====================Translate==============================
Cast list sẽ được hiển thị ở step 3
Tôi hiểu cái "same location area" rồi nhưng cho đến step3 thì vẫn chưa có button để user chọn area nên không biết được area của user.
Nhờ bên bạn xác nhận lại giúp tôi.
Và cái area này không liên quan gì đến "việc chọn 1 khu vực thường đến" phải không nhỉ?
Với lại cast list sẽ để hiển thị bao nhiêu cast nhỉ?
Nếu TH guest không "like" hay chỉ like 1,2 cast thì có hoàn tất thao tác ở đó được không?

**Comment by akitoshi** [comment]
@UyenTran95 

```
Step 3に表示されるキャストリストとは？
キャストリストは何件まで表示する？
いいねをせずに、もしくは一件、二件しかいいねをしない場合、「完了」を押せますか？
```

・Step1 で選択した「よく遊ぶ場所」= 自分の「居住地」
・同じ「居住地」のキャストが表示される
・表示するキャストの人数は最大10名まで
・いいね！を無しででも「完了可能」（0~5名）

![ScreenShot_2021-06-02_10 20 53](https://user-images.githubusercontent.com/113367/120409745-90f8e300-c38c-11eb-982b-92f357d27e24.png)

以上でお願いします。
