### ISSUE TITLE
[Design][EndUser] 1-7 Profile edit detail

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#42]
![image](https://user-images.githubusercontent.com/84315397/120425917-45990180-c399-11eb-9400-504b2e6b6d5e.png)
どちらの形をしましか？
@akitoshi

**Comment by akitoshi** [comment]
@UyenTran95

右側の方法でお願いします。 

![ScreenShot_2021-06-02_13 57 23](https://user-images.githubusercontent.com/113367/120426165-88afa080-c3aa-11eb-875e-b0541b0ac489.png)
