### ISSUE TITLE
[Design][EndUser] Chat - All

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#63]
![image](https://user-images.githubusercontent.com/84315397/120578854-acc5bd00-c450-11eb-8368-70dcdf257dd5.png)
1.
これは最後のメッセージの時間ですね。下記のように実装してOKでしょうか。
０秒〜59秒：たった今
1分~59分：1min,2min...59min
60分〜23時59分:1h, 2h, 3h...23h
24時〜：yyyy/mm/dd

2．
・メイン画像：
グループに参加しているメンバーのAvatarから、ランドムにしますか？若しくは自分のAvatarをメインにしますか？
・５メンバー以上のデザインもおねがいします。

３．
未読＝０場合、０を表示してOKですね。

**Comment by akitoshi** [comment]
@UyenTran95 

良いフィードバックありがとうございます。

![ScreenShot_2021-06-03_14 16 11](https://user-images.githubusercontent.com/113367/120591129-99c5e380-c476-11eb-8879-c96763011f7b.png)


```
1.
これは最後のメッセージの時間ですね。下記のように実装してOKでしょうか。
０秒〜59秒：たった今
1分~59分：1min,2min...59min
60分〜23時59分:1h, 2h, 3h...23h
24時〜：yyyy/mm/dd
```

↑上記でお願いします。


```
2．
・メイン画像：
グループに参加しているメンバーのAvatarから、ランドムにしますか？若しくは自分のAvatarをメインにしますか？
・５メンバー以上のデザインもおねがいします。
```

- [x] fix design 
5人以上のキャストの場合のデザイン追加しました。
https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=1%3A3867

チャットリストですが
・アバターは自分以外のキャストを表示
・グループチャットのタイトルにキャスト人数

上記でお願いします。



```
３．
未読＝０場合、０を表示してOKですね。
```
いえ、未読0の場合は非表示でお願いしたいです。
