### ISSUE TITLE
[Spec][End User] Profile detail, data request, area

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#64]
![image](https://user-images.githubusercontent.com/84315397/120588121-d5ee4980-c460-11eb-8d17-6fb50c2be604.png)
各項目のデータをご準備してお願いいたします。

**Comment by akitoshi** [comment]
@UyenTran95 

こちらのスプレッドシートに記載しております。
ご確認よろしくお願いします。
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1270657552

**Comment by UyenTran95** [comment]
@akitoshi 
ありがとうございます。
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1270657552&range=A5:J5

```
3 | 居住地
SignUp後のSetUp画面で活動エリア(都道府県)を入力 → 居住地に入力済み → 変更可能
```

現在のデザインの通りに、SetUp画面は`活動エリア(都道府県)を入力 `ではありません、
`東京、大阪、名古屋から１つを選択する`ということです。

何か相違は無いでしょうか。ご確認よろしくお願いします。

**Comment by UyenTran95** [comment]
@akitoshi 
CASTのプロフィールも、詳細プロフィールをクリックしたら、
![image](https://user-images.githubusercontent.com/84315397/120739514-cbdd5100-c51b-11eb-8779-c08adba948ee.png)

10項目から選択可能ですね。
ちょっと気になっていますが、

CASTの簡単プロフィール（TAG）で、
![image](https://user-images.githubusercontent.com/84315397/120739837-427a4e80-c51c-11eb-8506-df08ad8af208.png)
No.10 髪型とNo７お仕事もあります。大丈夫ですか？

また、つば焼きの投稿に関して
![image](https://user-images.githubusercontent.com/84315397/120740315-2f1bb300-c51d-11eb-8339-1734e338b2fd.png)
「フリーランス」は詳細プロフィール`No.7 お仕事`から取得しますか？

最後は、GUESTは男の人ですけど、No.10 髪型も入りますか？

**Comment by akitoshi** [comment]
@UyenTran95 

良いフィードバックありがとうございます。
こちらで変更しておきました（青色文字）
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1270657552


`1. 髪型について`
男女共用で使えるようにするために
少し項目を増えさせていただきました。

https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1270657552&range=E52


`2. No.7 お仕事`
こちらも男女共用で使えるようになっています。
少し数を減らしておきました。

![ScreenShot_2021-06-04_13 48 30](https://user-images.githubusercontent.com/113367/120747394-e6272700-c53b-11eb-8169-09870c752e03.png)


`3. エリアについて`

このビジネスですが
最初は大阪・愛知（名古屋）・東京の3都市からマーケティングを進めていきます。
ですので、エリアサイズの調整が難しいと思っています。

・隣の都道府県でもマッチングしたい
・でも、キャストとゲストのユーザー数が最初は少ない

ですので、
居住地と活動エリアを別にしても良いでしょうか？

活動エリアをベースで
キャスト・ゲストを表示させたいです。（居住地をベースにしない）

以前にスプレッドシートで入力した予約エリアをベースにします。
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=173471948

**Comment by UyenTran95** [comment]
居住地と活動エリアを別にすることを承知しました。

**Comment by UyenTran95** [comment]
Chốt:
List data cho màn edit profile detail
https://docs.google.com/spreadsheets/d/1hNB-Oc1seonhp5wsw0GScyixDagsKQSJ5L33a82LtBw/edit#gid=810715480

Điểm thay đổi:
- Màn https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=350%3A167
Mặc định 0項目/10項目の入力 => 0項目/12項目の入力

- Chú ý hai giá trị:
3,4 và 12. 12 là area khu vực để lấy giá trị recomend các cast cung khu vực. 3,4 chỉ là thông tin hiển thị thôi.
