### ISSUE TITLE
[Design][Enduser][Chat 1-1] Booking

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#68]
![image](https://user-images.githubusercontent.com/84315397/120619147-eb299f00-c485-11eb-9ba3-c6502ee6dbe2.png)
念のためです。確認します。

1.
開始日程→DatePicker→過去の日は選択不可

2.
設定時間：Listbox (Select)で選択
1時間, 2時間, 3時間, 4時間…10時間からSelect

3. 
合計：設定時間とCASTの1時間あたりの料金で　自動見積もり
#10 
下記の例は正しいですか？

1時間あたりの料：７,000P
開始時刻 : 9:00PM
予約時間 : 4時間
→

```
合計：33,000P
内訳：7,000P × ４時間　＋　5,000P（深夜料金）
内訳：7,000P × 2時間
※延長15分につき2,275Pが発生します（1P = 1.1円）
```

4.質問です。
`※延長15分につき2,275Pが発生します（1P = 1.1円）
`　
Castの1時間あたりの料金は７,000Pであれば、延長15分につき７,０００：４＝１，７５０
と認識しています。
間違いがないでしょうか？

**Comment by akitoshi** [comment]
@UyenTran95 


```
1. 開始日程→DatePicker→過去の日は選択不可
```
はい、過去は選択不可でお願いします。


```
2. 設定時間：Listbox (Select)で選択
1時間, 2時間, 3時間, 4時間…10時間からSelect
```
はい、1~10時間のSelectでお願いします。

```
3. 合計：設定時間とCASTの1時間あたりの料金で自動見積もり
```

こちらミスが無いように、スプレッドシートでシミュレーションしてみました。
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1951431203

ご確認お願いします。


```
4. ※延長15分につき2,275Pが発生します（1P = 1.1円） 　
Castの1時間あたりの料金は７,000Pであれば、延長15分につき７,０００：４＝１，７５０
と認識しています。
間違いがないでしょうか？
```

延長料金に関しては3割増というのを計算式に入れておりませんでした。
**1,750P x 1.3 = 2,275P**

下記の割増を組み込むことは可能でしょうか？

https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=1951431203&range=S7

**Comment by UyenTran95** [comment]
@akitoshi 説明はとてもわかりやすいです。ありがとうございます。了解ました。技術的に問題がないと思いますが。確認しますね。

- Pulldown chọn ngày bắt đầu: datetimepicker (ngày + giờ bắt đầu) - ko thể chọn ngày trong quá khứ
- Thời gian muốn đặt cast: pulldown từ 1 - 10 tiếng: 1時間, 2時間, 3時間, 4時間…10時間
- Tổng cộng:
Về spec phần này để không sai xót thì tôi có mô tả ở dưới đây: 
https://docs.google.com/spreadsheets/d/1hNB-Oc1seonhp5wsw0GScyixDagsKQSJ5L33a82LtBw/edit#gid=1951431203&range=F6:T22

**Comment by UyenTran95** [comment]
深夜料金がある場合、デザインはどうですか？下記はOKですか？
```
合計：33,000P
内訳：7,000P × ４時間　＋　5,000P（深夜料金）
内訳：7,000P × 2時間
※延長15分につき2,275Pが発生します（1P = 1.1円）
```
