### ISSUE TITLE
[Design][EndUser] Chat 1 -1 First Stamp Like

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#72]
![image](https://user-images.githubusercontent.com/84315397/120770141-0bba2d80-c548-11eb-83d3-8cb59b2981c3.png)
Messageをクリックすると、1−1Chat Roomを開いて、 First Stamp Likeを表示するという認識はあっています。

![image](https://user-images.githubusercontent.com/84315397/120770596-7ff4d100-c548-11eb-928e-252b18ec3ea3.png)

**Comment by akitoshi** [comment]
@UyenTran95 

Heart Button = いいね！ボタン を押す
→ 1on1のチャットルームが作成される
→ スタンプが追加されている状態
& "Message" ボタンに変更されている

Messageボタンを押す
→ チャットルームへ直接アクセスできる。

![ScreenShot_2021-06-07_16 40 07](https://user-images.githubusercontent.com/113367/120978302-4a9dec80-c7af-11eb-8c33-f9f37dd2d048.png)

という認識です。
