### ISSUE TITLE
[Design][Enduser] Guest - Call

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#73]
![image](https://user-images.githubusercontent.com/84315397/120989740-0eb45880-c7aa-11eb-85f1-094403360090.png)
場所のデータをご準備していただけませんか？

**Comment by akitoshi** [comment]
@UyenTran95 

場所データはこちらのスプレッドシートでご確認お願いします。
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=173471948

予約関連のデザインについては少し検討させてください。
![image](https://user-images.githubusercontent.com/113367/121108458-c0a06300-c844-11eb-856d-20ddf05e180c.png)
