### ISSUE TITLE
[Design][Enduser]Setup Step 3

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#74]
1. Step3で「完了」を押した後、どの画面に遷移しますか。Searchのホーム画面？
2. 10キャストリストに対して、いずれかのキャストをクリックしたら、詳細プロフィール画面を開きますか？
3. 「完了」を押した際、APIエラーにより（Firebaseに画像・データを保存できない）Step1に戻せます。その時、メッセージが必要です。その内容お願いします。

Sau khi nhấn "hoàn thành" ở step3 sẽ chuyển sang màn nào ạ? chuyển sang màn search - home có phải không?
Khi click vào cast bất kỳ nào trong 10 cast ở cast list cũng đề mở ra màn profile chi tiết của cast ạ?
Sau khi nhấn "hoàn thành" sẽ có một API error đưa về step1 (không thể lưu hình ảnh/ data vào Firebase). Lúc này sẽ cần hiển thị 1 message thì nội dung message là gì nhỉ? nhờ bạn chỉ rõ hơn giúp tôi!

**Comment by akitoshi** [comment]
@UyenTran95 

```
1. Step3で「完了」を押した後、どの画面に遷移しますか。Searchのホーム画面？
```
いえ、マイページへの遷移をお願いします。

```
2. 10キャストリストに対して、いずれかのキャストをクリックしたら、詳細プロフィール画面を開きますか？
```
はい、詳細プロフィールを開きます。
Step3で「いいね♡ボタン」があると、なかなか使い勝手が良くなさそうなので
削除するのはどうでしょうか？
代わりに、Select Button を追加しました。

![ScreenShot_2021-06-09_10 36 25](https://user-images.githubusercontent.com/113367/121280630-94064d00-c911-11eb-84aa-09960ce76bfb.png)


```
3. 「完了」を押した際、APIエラーにより（Firebaseに画像・データを保存できない）Step1に戻せます。その時、メッセージが必要です。その内容お願いします。
```
こちらでどうでしょうか？
https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=927%3A301

react-hot-toast での実装をイメージしてデザインしています。
https://react-hot-toast.com/

**Comment by UyenTran95** [comment]
1. Step3で「完了」を押した後、どの画面に遷移しますか。Searchのホーム画面？
2. 10キャストリストに対して、いずれかのキャストをクリックしたら、詳細プロフィール画面を開きますか？
3. 「完了」を押した際、APIエラーにより（Firebaseに画像・データを保存できない）Step1に戻せます。その時、メッセージが必要です。その内容お願いします。
==================Translate=========================
1. Sau khi nhấn "hoàn thành" ở step3 sẽ chuyển sang màn nào ạ? chuyển sang màn search - home có phải không?
2. Khi click vào cast bất kỳ nào trong 10 cast ở cast list cũng đề mở ra màn profile chi tiết của cast ạ?
3. Sau khi nhấn "hoàn thành" sẽ có một API error đưa về step1 (không thể lưu hình ảnh/ data vào Firebase). Lúc này sẽ cần hiển thị 1 message thì nội dung message là gì nhỉ? nhờ bạn chỉ rõ hơn giúp tôi!

**Comment by UyenTran95** [comment]
Answer:

1. Sau khi nhấn "hoàn thành" ở step3 sẽ chuyển sang màn nào ạ? chuyển sang màn search - home có phải không?
=> Không, sẽ cho trở về màn my page

2. Khi click vào cast bất kỳ nào trong 10 cast ở cast list cũng đề mở ra màn profile chi tiết của cast ạ?
=> Đúng rồi, sẽ mở ra chi tiết profile của cast
Tôi đang thấy nút "Like" ở step3 không dễ dùng lắm.
Xoá nút này đi thì sao nhỉ? Thay vào đó, tôi đã thêm một nút Select button.

3. Sau khi nhấn "hoàn thành" sẽ có một API error đưa về step1 (không thể lưu hình ảnh/ data vào Firebase). Lúc này sẽ cần hiển thị 1 message thì nội dung message là gì nhỉ? nhờ bạn chỉ rõ hơn giúp tôi!
=>  bạn xem ở đây nhé!
https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=927%3A301
tôi sử dụng hình ảnh ở react-hot-toast để design
https://react-hot-toast.com/
