### ISSUE TITLE
[Design][Enduser] Login/Register Set up For Cast 

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#75]
Castのログイン、登録、SetupなどはGuestと違いと思いますので、デザインをご準備して頂ければ幸いです。

**Comment by akitoshi** [comment]
@UyenTran95 

こちら用意しております。
Step2 のタグが異なりますが、ほぼゲストとほぼ同じです。
登録完了後はマイページに遷移してください。

Step2:  https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=927%3A521
MyPage(Cast): https://www.figma.com/file/xlkqRrCfMV9i4IP8ynh2cH/Nom?node-id=661%3A23
