### ISSUE TITLE
【C2Cエンタメマッチングサービス】[React]EndUser ＜1-9＞通知設定-おすすめユーザー | Setting thông báo - Suggest User 　 

### ISSUE THREAD

**Issue by UyenTran95** [akitoshi/Nom#9]
通知設定にて、確認させていただきます。
おすすめユーザーと記載されていますが

お客様がキャストを予約する機能に関係がありません。別の機能であると認識しています。

そうであれば、この機能に関する説明がありませんので、ご確認お願い致します。

**-----------------------------------Translate**
Về noti setting, tôi xin xác nhận như sau: Dù được ghi là suggest user nhưng nó không liên quan gì đến tính năng KH booking cast. Tôi đang hiểu nó là một tính năng riêng. Nếu thế thì vì chưa có phần giải thích nào cho tính năng này nên nhờ bạn xác nhận lại giúp.

**Comment by akitoshi** [comment]
おすすめユーザー

こちら説明不足していました。
PersonalizedなUserをおすすめすることは難しいと思うので
シンプルなロジックを想定しています。

"同じエリアでいいね！が多い人のTOP100をランダム表示"
https://docs.google.com/spreadsheets/d/1_9mjfO0_qxt4mc4uxI3Bybc-JSPcAvXPfDJ1fVq7M7w/edit#gid=772264952&range=G38

予約に関する通知機能ではなく、
ユーザーに1日1回はwebsiteへアクセスしてもらうための通知です。

機能優先度は高くありません。
